cities = [
    "New York, USA",
    "Toronto, Canada",
    "Mexico City, Mexico",
    "Vancouver, Canada",
    "Montreal, Canada",
    "Los Angeles, USA",
    "London, UK",
    "Paris, France",
    "Rome, Italy",
    "Madrid, Spain",
    "Berlin, Germany",
    "Amsterdam, Netherlands",
    "Vienna, Austria",
    "Zurich, Switzerland",
    "Athens, Greece",
    "Lisbon, Portugal",
    "Dublin, Ireland",
    "Stockholm, Sweden",
    "Oslo, Norway",
    "Helsinki, Finland",
    "Brussels, Belgium",
    "Copenhagen, Denmark",
    "Warsaw, Poland",
    "Budapest, Hungary",
    "Prague, Czech Republic",
    "Moscow, Russia",
    "Tokyo, Japan",
    "Shanghai, China",
    "Seoul, South Korea",
    "Beijing, China",
    "Mumbai, India",
    "Bangkok, Thailand",
    "Jakarta, Indonesia",
    "Istanbul, Turkey",
    "Tehran, Iran",
    "Dubai, United Arab Emirates",
    "Ho Chi Minh City, Vietnam",
    "Taipei, Taiwan",
    "Kuala Lumpur, Malaysia",
    "Singapore, Singapore",
    "Riyadh, Saudi Arabia",
    "Doha, Qatar",
    "Manila, Philippines",
    "Karachi, Pakistan",
    "Kolkata, India",
    "Hanoi, Vietnam",
]
